name: Bug report
description: Something does not work as expected
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant version
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Cookbook Menu version
    validations:
      required: true
  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics
      description: Settings > Devices & services > Cookbook Menu > Download diagnostics. Attach the file.
